export const STORE_TOKEN = 'STORE_TOKEN';
export const STORE_USER_DATA = 'STORE_USER_DATA';
export const STORE_DEPARTMENT_MEMBERS = 'STORE_DEPARTMENT_MEMBERS';
export const STORE_POST = 'STORE_POST';
export const STORE_LATEST_POSTS = 'STORE_LATEST_POSTS';
export const STORE_PREVIOUS_POSTS = 'STORE_PREVIOUS_POSTS';